### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by lxtGH** [msracver/Flow-Guided-Feature-Aggregation#15]
python: 2.7
mxnet:  v0.10.0
I run the demo but meet this error (I follow all the steps in the readme file)

Traceback (most recent call last):
  File "./fgfa_rfcn/demo.py", line 257, in <module>
    main()
  File "./fgfa_rfcn/demo.py", line 155, in main
    arg_params=arg_params, aux_params=aux_params)
  File "/home/lxt/Github/Flow-Guided-Feature-Aggregation/fgfa_rfcn/core/tester.py", line 32, in __init__
    self._mod.bind(provide_data, provide_label, for_training=False)
  File "/home/lxt/Github/Flow-Guided-Feature-Aggregation/fgfa_rfcn/core/module.py", line 839, in bind
    for_training, inputs_need_grad, force_rebind=False, shared_module=None)
  File "/home/lxt/Github/Flow-Guided-Feature-Aggregation/fgfa_rfcn/core/module.py", line 396, in bind
    state_names=self._state_names)
  File "/home/lxt/Github/Flow-Guided-Feature-Aggregation/fgfa_rfcn/core/DataParallelExecutorGroup.py", line 186, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/home/lxt/Github/Flow-Guided-Feature-Aggregation/fgfa_rfcn/core/DataParallelExecutorGroup.py", line 272, in bind_exec
    shared_group))
  File "/home/lxt/Github/Flow-Guided-Feature-Aggregation/fgfa_rfcn/core/DataParallelExecutorGroup.py", line 545, in _bind_ith_exec
    context, self.logger)
  File "/home/lxt/Github/Flow-Guided-Feature-Aggregation/fgfa_rfcn/core/DataParallelExecutorGroup.py", line 523, in _get_or_reshape
    arg_arr = nd.zeros(arg_shape, context, dtype=arg_type)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/ndarray.py", line 1003, in zeros
    return _internal._zeros(shape=shape, ctx=ctx, dtype=dtype)
  File "<string>", line 15, in _zeros
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/_ctypes/ndarray.py", line 72, in _imperative_invoke
    c_array(ctypes.c_char_p, [c_str(str(val)) for val in vals])))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/base.py", line 84, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [13:34:30] src/c_api/c_api_ndarray.cc:392: Operator _zeros cannot be run; requires at least one of FCompute<xpu>, NDArrayFunction, FCreateOperator be registered

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f724aa48f2c]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/libmxnet.so(MXImperativeInvoke+0x8c9) [0x7f724b7f5209]
[bt] (2) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f724deb0e40]
[bt] (3) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f724deb08ab]
[bt] (4) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7f724e0c03df]
[bt] (5) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7f724e0c4d82]
[bt] (6) python(PyObject_Call+0x43) [0x4b0c93]
[bt] (7) python(PyEval_EvalFrameEx+0x602f) [0x4c9f9f]
[bt] (8) python(PyEval_EvalCodeEx+0x255) [0x4c2705]
[bt] (9) python(PyEval_EvalFrameEx+0x686f) [0x4ca7df]

**Comment by lxtGH** [comment]
try to compile mxnet with CUDNN=1
https://github.com/msracver/FCIS/issues/51
and also put this repo into the root of mxnet
https://github.com/NVlabs/cub

**Comment by mamunir** [comment]
I tried to compile, same error occurs. Where to set CUDA=1 or CUDNN=1 for compilation?

Thanks

@lxtGH
