### ISSUE TITLE
ImportError: cannot import name bbox_overlaps_cython

### ISSUE THREAD

**Issue by wingNine** [msracver/Flow-Guided-Feature-Aggregation#20]
I run python ./fgfa_rfcn/demo.py
then have a problem,
Traceback (most recent call last):
  File "./fgfa_rfcn/demo.py", line 21, in <module>
    from utils.image import resize, transform
  File "/home/grade3_weiyun/projects/Flow-Guided-Feature-Aggregation-master/fgfa_rfcn/../lib/utils/image.py", line 6, in <module>
    from bbox.bbox_transform import clip_boxes
  File "/home/grade3_weiyun/projects/Flow-Guided-Feature-Aggregation-master/fgfa_rfcn/../lib/bbox/bbox_transform.py", line 3, in <module>
    from bbox import bbox_overlaps_cython
ImportError: cannot import name bbox_overlaps_cython

 how should i do?

**Comment by visionxyz** [comment]
Did you run "sh init.sh"?

**Comment by Feywell** [comment]
Duplicate of #https://github.com/msracver/Deep-Feature-Flow/issues/21

**Comment by melo19890618** [comment]
I also encountered this problem, would like to ask how to solve it, can only use python2?

**Comment by lfeifan2020** [comment]
I also meet this problem when use python3 anaconda3. I solved with building an environment about python2.7, it works well!
