### ISSUE TITLE
Error in demo.py and question about groundtruth_motion_iou

### ISSUE THREAD

**Issue by liangxi627** [msracver/Flow-Guided-Feature-Aggregation#34]
I test an image from my own dataset, and it occurs the following error in demo.py, how to solve it?
Another question is I want to finetune my own dataset, how to generate "groundtruth_motion_iou" file in config.py? Please help me~

> get-predictor
Traceback (most recent call last):
  File "/home/sipl03/lx/code/Flow-Guided-Feature-Aggregation-master/fgfa_rfcn/demo.py", line 259, in <module>
    main()
  File "/home/sipl03/lx/code/Flow-Guided-Feature-Aggregation-master/fgfa_rfcn/demo.py", line 232, in main
    pred_result = im_detect(aggr_predictors, data_batch, data_names, scales, cfg)
  File "/home/sipl03/lx/code/Flow-Guided-Feature-Aggregation-master/fgfa_rfcn/core/tester.py", line 144, in im_detect
    output_all = predictor.predict(data_batch)
  File "/home/sipl03/lx/code/Flow-Guided-Feature-Aggregation-master/fgfa_rfcn/core/tester.py", line 41, in predict
    self._mod.forward(data_batch)
  File "/home/sipl03/lx/code/Flow-Guided-Feature-Aggregation-master/fgfa_rfcn/core/module.py", line 1045, in forward
    shared_module=self._curr_module)
  File "/home/sipl03/lx/code/Flow-Guided-Feature-Aggregation-master/fgfa_rfcn/core/module.py", line 401, in bind
    state_names=self._state_names)
  File "/home/sipl03/lx/code/Flow-Guided-Feature-Aggregation-master/fgfa_rfcn/core/DataParallelExecutorGroup.py", line 191, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/home/sipl03/lx/code/Flow-Guided-Feature-Aggregation-master/fgfa_rfcn/core/DataParallelExecutorGroup.py", line 277, in bind_exec
    shared_group))
  File "/home/sipl03/lx/code/Flow-Guided-Feature-Aggregation-master/fgfa_rfcn/core/DataParallelExecutorGroup.py", line 494, in _bind_ith_exec
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-1.3.0-py2.7.egg/mxnet/symbol/symbol.py", line 996, in infer_shape
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-1.3.0-py2.7.egg/mxnet/symbol/symbol.py", line 1126, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-1.3.0-py2.7.egg/mxnet/base.py", line 255, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator concat0: [11:01:47] src/operator/nn/concat.cc:66: Check failed: shape_assign(&(*in_shape)[i], dshape) Incompatible input shape: expected [19,0,794,600], got [10,3,794,600]

**Comment by noirblack** [comment]
@liangxi627 Have you sloved it? I got a similar error during testing.

**Comment by liangxi627** [comment]
No, I have changed to another network.

**Comment by zhrjzrj** [comment]
I got a similar error. Anyone could help me?

**Comment by wangpichao** [comment]
> @liangxi627 Have you sloved it? I got a similar error during testing.

Have you solved this issue?

**Comment by wangpichao** [comment]
> I got a similar error. Anyone could help me?
Have you solved this issue?

**Comment by wangpichao** [comment]
> I got a similar error. Anyone could help me?

Have you solved this issue?

**Comment by wangpichao** [comment]
> I got a similar error. Anyone could help me?

@zhrjzrj Have you solved this issue?

**Comment by wangpichao** [comment]
@liangxi627 @zhrjzrj @noirblack please make sure that your video sequence is longer than 19 (2*KEY_FRAME_INTERVAL+1), if the KEY_FRAME_INTERVAL = 9.

**Comment by Gmy12138** [comment]
@liangxi627   @wangpichao @zhrjzrj @noirblack @YuwenXiong  you know how to generate "groundtruth_motion_iou" file？

**Comment by Sanku-Yogesh** [comment]
@wangpichao @liangxi627 @noirblack @zhrjzrj @Gmy12138  Could u please refer to this issues https://github.com/Scalsol/mega.pytorch/issues/73#issue-754884469

**Comment by zhrjzrj** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
