### ISSUE TITLE
 'module' object has no attribute 'PSROIPooling'

### ISSUE THREAD

**Issue by ron5569** [msracver/Flow-Guided-Feature-Aggregation#65]
Traceback (most recent call last):
  File "./fgfa_rfcn/demo.py", line 257, in <module>
    main()
  File "./fgfa_rfcn/demo.py", line 99, in main
    aggr_sym = aggr_sym_instance.get_aggregation_symbol(cfg)
  File "/home/indoordesk/project/Flow-Guided-Feature-Aggregation/fgfa_rfcn/symbols/resnet_v1_101_flownet_rfcn.py", line 1128, in get_aggregation_symbol
    psroipooled_cls_rois = mx.contrib.sym.PSROIPooling(name='psroipooled_cls_rois', data=rfcn_cls, rois=rois,
AttributeError: 'module' object has no attribute 'PSROIPooling'

Does someone know how to handle this error?

**Comment by kayser-soze** [comment]
You probably did not compile the mxnet from source with the needed operators.
Try this https://github.com/msracver/Flow-Guided-Feature-Aggregation/issues/68#issue-570612160
