### ISSUE TITLE
error in function vid_eval_motion: What is  motion_iou ??

### ISSUE THREAD

**Issue by ron5569** [msracver/Flow-Guided-Feature-Aggregation#69]
Hey I'm trying to evaluate  my model but I get the following error:

eval_vid_detection :: accumulating: motion [0.0 1.0], area [0.0 0.0 100000.0 100000.0]

Traceback (most recent call last):
  File "experiments/fgfa_rfcn/fgfa_rfcn_end2end_train_test.py", line 21, in <module>
    test.main()
  File "experiments/fgfa_rfcn/../../fgfa_rfcn/test.py", line 58, in main
    enable_detailed_eval=config.dataset.enable_detailed_eval)
  File "experiments/fgfa_rfcn/../../fgfa_rfcn/function/test_rcnn.py", line 90, in test_rcnn
    pred_eval_multiprocess(gpu_num, feat_predictors, aggr_predictors, test_datas, imdb, cfg, vis=vis, ignore_cache=ignore_cache, thresh=thresh, logger=logger)
  File "experiments/fgfa_rfcn/../../fgfa_rfcn/core/tester.py", line 386, in pred_eval_multiprocess
    info_str = imdb.evaluate_detections_multiprocess(res)
  File "experiments/fgfa_rfcn/../../fgfa_rfcn/../lib/dataset/imagenet_vid.py", line 243, in evaluate_detections_multiprocess
    info = self.do_python_eval_gen()
  File "experiments/fgfa_rfcn/../../fgfa_rfcn/../lib/dataset/imagenet_vid.py", line 429, in do_python_eval_gen
    motion_ranges, area_ranges, ovthresh=0.5)
  File "experiments/fgfa_rfcn/../../fgfa_rfcn/../lib/dataset/imagenet_vid_eval_motion.py", line 240, in vid_eval_motion
    if ig_gt_motion[k] & (ov > ovmax_ig):
IndexError: list index out of range

Im trying to undrstand what is the function vid_eval_motion, but it looks so complicated.
Anybody can explain what is the function do, and why I get this error?

**Comment by ron5569** [comment]
Ok I think it happen since I use my own dataset, with multiple object in a image.
However it stil not clear for me what is motion_iou and what its value represented.
Thanks!

**Comment by bhumit04** [comment]
Hi, I am getting the same error during the testing of my FGFA implementation. How did you get around this error? I have been stuck on this error for some time.

**Comment by halcyonway** [comment]
@ron5569 @bhumit04  hi guys, I think `motion iou` is an indicator which represent object's speed according its paper,
>> An object’s speed is measured by its averaged intersection-over-union (IoU) scores with its corresponding instances in the nearby frames (±10 frames). The indicator is dubbed as “motion IoU”.

**However** I encounter the same error as yours.  How did you solve this problem?  Please give me a favor~

**Comment by Sanku-Yogesh** [comment]
what is the size of total dataset VID and DET? can u give me exact link or please refer to this https://github.com/Scalsol/mega.pytorch/issues/73#issue-754884469
